import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderLayout from "@/layout/HeaderLayout";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { StrictMode } from "react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Polonia",
  description: "Generated by create next app",
  icons: {
    icon: "/Polonia.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <StrictMode>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${inter.className} antialiased bg-white overflow-x-hidden`}
          >
            <GoogleOneTap 
              fedCmSupport={false}
            />
            <HeaderLayout />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </StrictMode>
  );
}
