import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderLayout from "@/layout/HeaderLayout";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Polonia",
  description: "Generated by create next app",
  icons: {
    icon: "/Polonia.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <ClerkProvider publishableKey="">
      <html lang="en">
        <body
          className={`${inter.className} antialiased bg-white overflow-x-hidden`}
        >
          <HeaderLayout />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
