import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderLayout from "@/layout/HeaderLayout";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { StrictMode } from "react";
import QueryContext from "@/context/QueryContext";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Polonia",
  description: "Generated by create next app",
  icons: {
    icon: "/Polonia.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en">
      <QueryContext>
        <ClerkProvider>
          <body
            className={`${inter.className} antialiased bg-white overflow-x-hidden relative`}
          >
            <HeaderLayout />
            {children}
          </body>
          <ReactQueryDevtools initialIsOpen={true} />
        </ClerkProvider>
      </QueryContext>
    </html>

  );
}
